version: '3'
services:
  backend:
    build:
      context: ./footballleagueback/
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - common_network
  front:
    build:
      context: ./footballLeagueFront/
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "9000:80"
    networks:
      - common_network

networks:
  common_network:
    name: network_a
  