# Generated by Django 3.1.2 on 2020-10-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.club')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_minute', models.IntegerField()),
                ('team', models.CharField(choices=[('HOME', 'home'), ('AWAY', 'away')], max_length=255)),
                ('footballer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.footballer')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('result', models.CharField(choices=[('HOMEWIN', 'home win'), ('AWAYWIN', 'away win'), ('DRAW', 'draw')], max_length=255)),
                ('away_side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.club')),
                ('goals', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.goal')),
                ('home_side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.club')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.match'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='goals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.goal'),
        ),
        migrations.AddField(
            model_name='club',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.footballer'),
        ),
    ]
