# Generated by Django 3.1.2 on 2020-12-05 11:20

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import league.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('position', enumchoicefield.fields.EnumChoiceField(enum_class=league.enums.Position, max_length=10)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.club')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchDate', models.DateField()),
                ('result', enumchoicefield.fields.EnumChoiceField(enum_class=league.enums.Result, max_length=7)),
                ('awaySide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.club')),
                ('homeSide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.club')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalMinute', models.IntegerField()),
                ('side', enumchoicefield.fields.EnumChoiceField(enum_class=league.enums.Side, max_length=4)),
                ('footballer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.footballer')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='league.match')),
            ],
        ),
        migrations.AddField(
            model_name='footballer',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.goal'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.club'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('side', enumchoicefield.fields.EnumChoiceField(enum_class=league.enums.Side, max_length=4)),
                ('reason', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(league.enums.CardType(1), 1), (league.enums.CardType(2), 2)], max_length=255)),
                ('footballer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.footballer')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='league.match')),
            ],
        ),
    ]
